name: inception

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    networks:
      - inception-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_URL: ${DOMAIN_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_USER_LOGIN: ${WORDPRESS_USER_LOGIN}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_admin_password
    secrets:
       - db_password
       - wp_admin_password
       - wp_user_password
    networks:
      - inception-network

  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
    volumes:
      - "/home/${LOGIN}/Inception/srcs/requirements/tools/${SSL_CERTIFICATE}:\
          /etc/nginx/${SSL_CERTIFICATE}"
      - "/home/${LOGIN}/Inception/srcs/requirements/tools/${SSL_KEY}:\
          /etc/nginx/${SSL_KEY}"
      - "/home/${LOGIN}/Inception/srcs/requirements/nginx/conf/\
          default.conf.template:/etc/nginx/templates/default.conf.template"
      - wordpress:/var/www/html
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE}
      SSL_KEY: ${SSL_KEY}
    ports:
      - "443:443"
    networks:
      - inception-network

networks:
  inception-network:
    name: inception-network
    driver: bridge

secrets:
   db_password:
     file: ../secrets/db_password.txt
   db_root_password:
     file: ../secrets/db_root_password.txt
   wp_admin_password:
     file: ../secrets/wp_admin_password.txt
   wp_user_password:
     file: ../secrets/wp_user_password.txt

volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: "/home/${LOGIN}/data/wordpress"
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: "/home/${LOGIN}/data/mariadb"
