#!/usr/bin/env ansible-playbook
---
- name: Inception setup for Ubuntu
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:

    - name: "Gather only facts returned by \
        architecture, distribution, os_family, user_dir, user_id"
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - architecture
          - distribution
          - os_family
          - user_dir
          - user_id
      become: false

    - name: "Ensure that OS family is Debian and \
            that architecture and distribution are defined"
      ansible.builtin.assert:
        that:
          - ansible_architecture is defined
          - ansible_distribution is defined
          - ansible_os_family == "Debian"
        quiet: true

    - name: Set Ansible architecture
      ansible.builtin.set_fact:
        ansible_architecture: "\
          {{ 'amd64' if ansible_architecture == 'x86_64' \
          else 'arm64' if ansible_architecture == 'aarch64' \
          else ansible_architecture }}"

    - name: Update installed packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
        clean: true

    - name: Install unattended-upgrades, sudo, git and make packages
      ansible.builtin.apt:
        name:
          - unattended-upgrades
          - sudo
          - git
          - make
        state: latest

    - name: Edit /etc/apt/apt.conf.d/02periodic
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/02periodic
        line: "{{ item }}"
        create: true
      loop:
        - 'APT::Periodic::Enable "1";'
        - 'APT::Periodic::Update-Package-Lists "1";'
        - 'APT::Periodic::Download-Upgradeable-Packages "1";'
        - 'APT::Periodic::Unattended-Upgrade "1";'
        - 'APT::Periodic::AutocleanInterval "1";'
        - 'APT::Periodic::Verbose "1";'

    - name: Edit /etc/sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^Defaults\t{{ item.key }}"
        insertafter: '^Defaults'
        line: "Defaults\t{{ item.value }}"
      loop:
        - { key: 'passwd_tries', value: 'passwd_tries=3' }
        - { key: 'log_input', value: 'log_input' }
        - { key: 'log_output', value: 'log_output' }
        - { key: 'iolog_dir', value: 'iolog_dir="/var/log/sudo"' }
        - { key: 'requiretty', value: 'requiretty' }

    - name: Set dotfiles git directory
      ansible.builtin.set_fact:
        dotfiles_git_directory: "{{ ansible_user_dir }}/.dotfiles"

    - name: Download dotfiles
      ansible.builtin.git:
        repo: https://github.com/abdelbenamara/dotfiles.git
        dest: "{{ dotfiles_git_directory }}"
        single_branch: true
        update: false
      become: false

    - name: Make dotfiles
      community.general.make:
        chdir: "{{ dotfiles_git_directory }}"
      become: false

    - name: Install ca-certificates and curl packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: latest

    - name: Create /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker official GPG key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/\
          {{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: Edit /etc/apt/sources.list.d/docker.list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ ansible_architecture }} \
          signed-by=/etc/apt/keyrings/docker.asc] \
          https://download.docker.com/linux/{{ ansible_distribution | lower }} \
          {{ ansible_distribution_release }} stable"
        create: true

    - name: Update installed packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
        clean: true

    - name: "Install docker-ce, docker-ce-cli, containerd.io, \
        docker-buildx-plugin and docker-compose-plugin packages"
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Download Inception
      ansible.builtin.git:
        repo: https://github.com/abdelbenamara/Inception.git
        dest: "{{ ansible_user_dir }}/Inception"
        single_branch: yes
        update: false
      become: false

    - name: Create Inception/srcs/.env from Inception/srcs/template.env
      ansible.builtin.copy:
        src: "{{ ansible_user_dir }}/Inception/srcs/template.env"
        dest: "{{ ansible_user_dir }}/Inception/srcs/.env"
      become: false

    - name: Edit Inception/srcs/.env
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/Inception/srcs/.env"
        regexp: '^LOGIN'
        line: "LOGIN={{ ansible_user_id }}"
      become: false

    - name: Set common name (CN)
      ansible.builtin.set_fact:
        common_name: "{{ ansible_user_id }}.42.fr"

    - name: Create requirements tools directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/Inception/srcs/requirements/tools"
        state: directory
      become: false

    - name: Set ssl certificates paths
      ansible.builtin.set_fact:
        ssl_common_path: "{{ ansible_user_dir }}/\
          Inception/srcs/requirements/tools/{{ common_name }}"

    - name: Generate an OpenSSL private keys for CA and certificate
      community.crypto.openssl_privatekey:
        path: "{{ ssl_common_path }}{{ item }}.key"
      loop:
        - ".ca"
        - ""
      become: false

    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ssl_common_path }}.ca.key"
        country_name: 'FR'
        state_or_province_name: 'Ile-de-France'
        locality_name: 'Paris'
        organization_name: '42'
        organizational_unit_name: '42 School'
        common_name: "{{ common_name }}"
        use_common_name_for_san: false
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr

    - name: Create self-signed CA certificate from its CSR
      community.crypto.x509_certificate:
        path: "{{ ssl_common_path }}.ca.crt"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "{{ ssl_common_path }}.ca.key"
        provider: selfsigned
      become: false

    - name: Create certificate signing request (CSR) for new certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ssl_common_path }}.key"
        common_name: "{{ common_name }}"
        organization_name: '42'
        organizational_unit_name: 'Inception'
        subject_alt_name:
          - 'DNS:127.0.0.1'
          - 'DNS:localhost'
          - "DNS:{{ common_name }}"
          - "DNS:*.{{ common_name }}"
      register: crt_csr

    - name: Generate a certificate signed with owned CA certificate
      community.crypto.x509_certificate:
        path: "{{ ssl_common_path }}.crt"
        csr_content: "{{ crt_csr.csr }}"
        ownca_not_after: "+365d"
        ownca_not_before: "-1d"
        ownca_path: "{{ ssl_common_path }}.ca.crt"
        ownca_privatekey_path: "{{ ssl_common_path }}.ca.key"
        provider: ownca
      become: false

    - name: Create secrets directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/Inception/secrets"
        state: directory
      become: false

    - name: Edit secrets
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/Inception/secrets/{{ item }}.txt"
        regexp: '^.*$'
        line: "{{ lookup('ansible.builtin.password', '/dev/null', length=64) }}"
        create: true
      loop:
        - "db_password"
        - "db_root_password"
        - "redis_default_password"
        - "redis_password"
        - "wordpress_admin_password"
        - "wordpress_user_password"
        - "ftp_password"
        - "django_secret_key"
      become: false

    - name: Create volumes directories
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/data/{{ item }}"
        state: directory
      loop:
        - "mariadb"
        - "redis"
        - "wordpress"
        - "django"
        - "adminer"
        - "uptime-kuma"
      become: false

    - name: Make Inception
      community.general.make:
        chdir: "{{ ansible_user_dir }}/Inception"
        targets:
          - all
          - hosts
    
    - name: Install filezilla package
      ansible.builtin.apt:
        name: filezilla
        state: latest

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true
